workflows:
  flutter_build:
    name: "Flutter Build"
    scripts:
      - name: "Install dependencies"
        script: flutter pub get
      - name: "Build flutter build web --web-renderer html --release"
        script: flutter build web --web-renderer html --release
                cd build/web
                7z a -r ../web.zip ./*
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'dev_branch'
          include: true
          source: true