workflows:
  flutter_build:
    name: "Flutter Build"
    scripts:
      - name: "Install dependencies"
        script: flutter pub get
      - name: "Build APK"
        script: flutter build apk
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'dev_branch'
          include: true
          source: true